spring.application.name=SmartBancsApp

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/smartbancs}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:smartbancs}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:smartbancs_local}
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
